### ISSUE TITLE
Question about the API parameters

### ISSUE THREAD

**Issue by jack-zheng** [dpy1123/coupon#3]
Hi dpy1123,

我有个问题， 就是BiliBiliTest.java 这个class 里面我看到你调用了一个archive 的API， 但是我从B 站上filter 的时候发现他们在调用的时候是这样的
http://api.bilibili.com/archive_rank/getarchiverankbypartion?callback=jQuery172021296425229601046_1483432443320&type=jsonp&tid=27&pn=1&_=1483432443579
我的问题是你是怎么知道它传递的参数是type + uid + pn 的， 是根据上面的那个连接后面的参数猜测试出来的吗？

Thanks,
--Jack

**Comment by dpy1123** [comment]
你找的好仔细。。。test下面的内容都是纯test的，成品的在ArchiveTask里有~
接口都是访问b站的时候抓的，像type有jsonp一般就有json，试试就可以了~
